- name: Install apache2 package.
  apt:
    name: apache2
    state: present
  tags:
    - Apache2

- name: Copy {{ RAC_APP_URL }} configuration files in sites-available directory.
  template:
    src: apache/rac.conf.j2
    dest: /etc/apache2/sites-available/{{ RAC_APP_URL }}.conf
  tags:
    - Apache2

- name: Copy {{ RAC_APP_URL }} SSL configuration files in sites-available directory.
  template:
    src: apache/rac-ssl.conf.j2
    dest: /etc/apache2/sites-available/{{ RAC_APP_URL }}-ssl.conf
  tags:
    - Apache2
    

- name: Make sure the {{ RAC_APP_URL }} directory is present on server.
  file:
    path: "{{ RAC_APP_DOC_ROOT }}"
    state: directory
    mode: '0755'
    owner: www-data
    group: www-data
  tags:
    - Apache2    



- name: Make sure the {{ CLAVIS_APP_URL }} directory is present on server.
  file:
    path: /var/www/html
    state: directory
    mode: '0755'
    owner: www-data
    group: www-data
  tags:
    - Apache2    

- name: Install a libjose package from the internet.
  apt:
    deb: https://github.com/zmartzone/mod_auth_openidc/releases/download/v2.3.11/libcjose0_0.6.1.4-1.xenial+1_amd64.deb
  when: ansible_distribution == 'Ubuntu' or ansible_distribution_version == '16.04'

- name: Install a libapache2-mod-auth-openidc package from the internet.
  apt:
    deb: https://github.com/zmartzone/mod_auth_openidc/releases/download/v2.3.11/libapache2-mod-auth-openidc_2.3.11-1.xenial+1_amd64.deb
  when: ansible_distribution == 'Ubuntu' or ansible_distribution_version == '16.04'

- name: Enable Apache modules.
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - rewrite
    - proxy
    - proxy_http
    - proxy_balancer
    - proxy_fcgi
    - proxy_http
    - ssl
    - headers
    - auth_openidc
  tags:
    - Apache2 


- name: enable the apache site for {{ RAC_APP_URL }} in apache2.
  command: a2ensite {{ RAC_APP_URL }}
  args:
    creates: /etc/apache2/sites-enabled/{{ RAC_APP_URL }}.conf
  notify: Restart Apache2
  tags:
    - Apache2

- name: enable the apache site for {{ RAC_APP_URL }} SSL in apache2.
  command: a2ensite {{ RAC_APP_URL }}-ssl
  args:
    creates: /etc/apache2/sites-enabled/{{ RAC_APP_URL }}-ssl.conf
  notify: Restart Apache2
  tags:
    - Apache2

# - name: Copy {{ CLAVIS_APP_URL }} configuration files in sites-available directory.
#   template:
#     src: apache/clavis.conf.j2
#     dest: /etc/apache2/sites-available/{{ CLAVIS_APP_URL }}.conf
#   tags:
#     - Apache2

- name: Copy {{ CLAVIS_APP_URL }}-ssl configuration files in sites-available directory.
  template:
    src: apache/clavis-ssl.conf.j2
    dest: /etc/apache2/sites-available/{{ CLAVIS_APP_URL }}-ssl.conf
  tags:
    - Apache2    

- name: Remove Default files.
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  tags:
    - Apache2


- name: Setting up Letsencrypt for Rac-dev.pst.ag.
  copy:
    src: "{{ MAIN_BACKUP_FOLDER }}/letsencrypt"
    dest: /etc/
    owner: root
    group: root
    validate:  ls -ld /etc/letsencrypt %s
  tags:
    - Apache2
    - ssl


- name: Start service Apache2, if not started
  service:
    name: apache2
    state: started
    enabled: yes
  tags:
    - Apache2